version: "3.8"

services:
  frontend:
    build: ./fe
    container_name: fe
    ports:
      - "80:80"
      - "443:443"
  backend:
    build: ./be
    container_name: be
    ports:
      - "5000:5000"
